name: faust_calculator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.7
  pdf: ^3.6.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
