name: faust_calculator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  pdf: ^3.11.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
